# -*- coding: utf-8 -*-
"""PythonAssignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TEW49_xRhjyezB_1Wf8dVVdFrk_e1Y0
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ------------------ Q1: Student Registration & Grade Evaluation ------------------
def student_registration():
    student_name = input("Enter student name: ")
    score = float(input("Enter exam score (0-100): "))

    if score >= 90 and score <= 100:
        grade, remark = "A", "Excellent"
    elif score >= 75:
        grade, remark = "B", "Very Good"
    elif score >= 60:
        grade, remark = "C", "Good"
    elif score >= 40:
        grade, remark = "D", "Average"
    else:
        grade, remark = "F", "Needs Improvement"

    print("\n--- Student Report ---")
    print("Name:", student_name)
    print("Score:", score)
    print("Grade:", grade)
    print("Performance Remark:", remark)

# ------------------ Q2: Course Enrollment ------------------
def course_enrollment():
    courses = []
    max_courses = 5
    print("=== Course Enrollment System ===")
    while True:
        if len(courses) >= max_courses:
            print("Maximum course limit reached!")
            break
        course_name = input("Enter course name (or 'done' to finish): ")
        if course_name.lower() == "done":
            break
        credits = input("Enter credit value: ")
        if not credits.isdigit() or int(credits) <= 0:
            print("Invalid credit value! Skipping entry...")
            continue
        courses.append((course_name, int(credits)))
        print(f"Course '{course_name}' added.\n")

    print("\n--- Enrollment Report ---")
    for course, credit in courses:
        print(f"Course: {course}, Credits: {credit}")
    print("Total courses enrolled:", len(courses))

# ------------------ Q3: Student Records & Events ------------------
def student_records():
    students = [
        {"name": "Priya", "age": 20, "grades": [85, 90, 78]},
        {"name": "Rahul", "age": 21, "grades": [72, 88, 91]},
        {"name": "Anita", "age": 19, "grades": [95, 89, 92]}
    ]
    print("=== Student Records ===")
    for s in students:
        print(f"Name: {s['name']}, Age: {s['age']}, Grades: {s['grades']}")

    event_A = {"Priya", "Rahul", "Anita", "Kiran"}
    event_B = {"Rahul", "Anita", "Sneha"}
    print("\n=== Event Participation Analysis ===")
    print("Common Participants:", event_A & event_B)
    print("All Participants:", event_A | event_B)
    print("Only Event A Participants:", event_A - event_B)

# ------------------ Q4: Sorting & Searching ------------------
def sorting_searching():
    student_ids = [105, 102, 110, 108, 101, 115]
    print("Original IDs:", student_ids)

    # Bubble Sort
    for i in range(len(student_ids)):
        for j in range(0, len(student_ids)-i-1):
            if student_ids[j] > student_ids[j+1]:
                student_ids[j], student_ids[j+1] = student_ids[j+1], student_ids[j]
    print("Sorted IDs (Bubble Sort):", student_ids)

    # Linear Search
    target = int(input("Enter ID to search: "))
    if target in student_ids:
        print("Linear Search: ID found at index", student_ids.index(target))
    else:
        print("Linear Search: ID not found")

    # Binary Search
    low, high = 0, len(student_ids)-1
    found = False
    while low <= high:
        mid = (low + high) // 2
        if student_ids[mid] == target:
            print("Binary Search: ID found at index", mid)
            found = True
            break
        elif student_ids[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    if not found:
        print("Binary Search: ID not found")

# ------------------ Q5: Fee Calculation ------------------
def fee_calculation():
    tuition = int(input("Enter tuition fee: "))
    hostel = int(input("Enter hostel fee (0 if none): "))
    transport = int(input("Enter transport fee (0 if none): "))
    total = tuition + hostel + transport
    print("Total Fee:", total)

# ------------------ Q6: File Handling ------------------
def file_handling():
    with open("student_records.txt", "w") as f:
        f.write("ID,Name,Marks\n101,Arjun,85\n102,Meera,92\n103,Ravi,76\n104,Anita,89\n")
    print("Records written to file.")

    with open("student_records.txt", "r") as f:
        records = f.readlines()
    print("\nStored Records:")
    for r in records:
        print(r.strip())

    total_students, total_marks, highest_marks = 0, 0, -1
    top_student = ""
    for rec in records[1:]:
        _, name, marks = rec.strip().split(",")
        marks = int(marks)
        total_students += 1
        total_marks += marks
        if marks > highest_marks:
            highest_marks, top_student = marks, name
    print("\nReport:")
    print("Total Students:", total_students)
    print("Average Marks:", total_marks/total_students)
    print("Top Student:", top_student, "with", highest_marks)

# ------------------ Q7: Directory Scanning with Graph ------------------
class MissingFileOrFolderError(Exception):
    pass

def scan_directory(path):
    try:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Invalid path: {path}")

        folder_counts = {}  # store folder -> file count

        for root, dirs, files in os.walk(path):
            print(root)
            for f in files:
                print("   ", f)
            folder_counts[root] = len(files)

            if not files and not dirs:
                raise MissingFileOrFolderError(f"Empty folder: {root}")

        # --- Plotting the graph ---
        if folder_counts:
            plt.bar(folder_counts.keys(), folder_counts.values())
            plt.xticks(rotation=45, ha="right")
            plt.title("Files per Folder")
            plt.xlabel("Folders")
            plt.ylabel("Number of Files")
            plt.tight_layout()
            plt.show()

    except Exception as e:
        print("Error:", e)


# ------------------ Q8: Performance Analysis ------------------
def performance_analysis():
    try:
        df = pd.read_csv("student_performance.csv")
        print(df.describe())
        scores = df[["Math","Science","English"]].to_numpy()
        print("Mean:", np.mean(scores, axis=0))
        print("Median:", np.median(scores, axis=0))
        print("Std Dev:", np.std(scores, axis=0))
        df.plot(x="Name", y=["Math","Science","English"], kind="bar")
        plt.show()
    except Exception as e:
        print("Error:", e)

# ------------------ Main Dashboard ------------------
def main():
    while True:
        print("\n=== Smart Campus Information System ===")
        print("1. Student Registration & Grade Evaluation")
        print("2. Course Enrollment")
        print("3. Student Records & Events")
        print("4. Sorting & Searching IDs")
        print("5. Fee Calculation")
        print("6. File Handling")
        print("7. Directory Scanning")
        print("8. Performance Analysis")
        print("9. Exit")
        choice = input("Enter choice: ")
        if choice == "1": student_registration()
        elif choice == "2": course_enrollment()
        elif choice == "3": student_records()
        elif choice == "4": sorting_searching()
        elif choice == "5": fee_calculation()
        elif choice == "6": file_handling()
        elif choice == "7": scan_directory(input("Enter directory path: "))
        elif choice == "8": performance_analysis()
        elif choice == "9": break
        else: print("Invalid choice!")

if __name__ == "__main__":
    main()